(library
 (name utopia_runtime))

(install
 (section lib)
 (package utopia)
 (files
  (files/ReactServerDOMEsbuild.re as utopia_runtime/ReactServerDOMEsbuild.re)
  (files/FunctionReferences.re as utopia_runtime/FunctionReferences.re)
  (files/Utopia.re as utopia_runtime/Utopia.re)
  (files/Utopia_call_server_source_support.re as utopia_runtime/Utopia_call_server_source_support.re)
   (files/Utopia_route.ml as utopia_runtime/Utopia_route.ml)
   (files/Utopia_route_builder.ml as utopia_runtime/Utopia_route_builder.ml)
   (files/esbuild.config.mjs as utopia_runtime/esbuild.config.mjs)
   (../server/server.ml as utopia_runtime/Utopia_server.ml)
  (../utopia_types/utopia_types.ml as utopia_runtime/Utopia_types.ml)
  (files/Utopia_router.re as utopia_runtime/Utopia_router.re)
  (files/Utopia_router_link.re as utopia_runtime/Utopia_router_link.re)
  (files/Utopia_router_route.re as utopia_runtime/Utopia_router_route.re)
  (files/client_entry.re as utopia_runtime/client_entry.re)))
